apiVersion: v1
kind: Pod
metadata:
  name: app-pod-cmline
spec:
  containers:
  - name: app-container-cmline
    image: busybox
    args: [ "sh", "-c", "echo Mode: $APP_MODE; echo Secret: $APP_SECRET; sleep 3600" ]
    env:
    - name: APP_MODE
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_MODE
    - name: APP_SECRET
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: APP_SECRET